name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [ '3.0', '3.1', '3.2', '3.3', jruby, truffleruby ]
        rack: [ '2', '3' ]

    env:
      RACK_VERSION: ${{ matrix.rack }}

    steps:
    - uses: actions/checkout@v4

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - run: bundle exec rspec
